name: TERUpload

on:
    push:
        tags:
            - "**"

jobs:
    TERUpload:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v1

            - name: Mark repository as safe
              run: git config --global --add safe.directory /github/workspace

            - uses: tomasnorre/typo3-upload-ter@v2
              with:
                  api-token: ${{ secrets.TYPO3_API_TOKEN }}
